name = "nimiq_rpc"
version = "2.0.0"
description = "Nimiq JSON-RPC Client Library for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "sisou", repo = "gleam-nimiq-rpc" }
links = [
  { title = "Developer Center JSON-RPC Docs", href = "https://www.nimiq.com/developers/build/set-up-your-own-node/rpc-docs/" },
  { title = "NimiqHub JSON-RPC Docs", href = "https://www.nimiqhub.com/docs/rpc" }
]

[dependencies]
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
youid = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
dot_env = ">= 1.2.0 and < 2.0.0"
gleeunit = ">= 1.4.0 and < 2.0.0"
